app = "velox"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[env]
  NEXT_PUBLIC_SUPABASE_URL = "${SUPABASE_URL}"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "${SUPABASE_ANON_KEY}"
  SUPABASE_SERVICE_KEY = "${SUPABASE_SERVICE_KEY}"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "30s"
  timeout = "5s"
  grace_period = "10s"
  method = "GET"
  path = "/"
  protocol = "http"
  tls_skip_verify = false 