name: E2E

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
  workflow_dispatch:

concurrency:
  group: e2e-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Enable corepack
        run: corepack enable && corepack prepare pnpm@latest --activate
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Install Playwright browsers
        run: pnpm -w spec:install
      - name: Run Playwright E2E
        env:
          SPEC_BASE_URL: http://localhost:3001
        run: pnpm -w spec:e2e
      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: spec-report/html


